package com.example.demoapplication.data

import kotlin.reflect.KProperty

// COROUTINE BUILDERS EXPLAINED

fun main() {
    println("=== equals() and hashCode() Contract Clarification ===")
    demonstrateEqualsHashCodeContract()
    
    println("\n=== Contract Failure in Regular Classes with Inheritance ===")
    demonstrateContractFailureWithInheritance()
    
    println("\n=== Contract Failure in Regular Classes ===")
    demonstrateContractFailureInRegularClasses()
    
    println("\n=== Does equals() Use hashCode() Internally? ===")
    demonstrateEqualsAndHashCodeIndependence()
    
    println("\n=== WHY DATA CLASSES CANNOT BE INHERITED ===")
    demonstrateWhyDataClassesCannotBeInherited()
    
    println("\n=== Your Person Example ===")
    val person = Person("John", "Doe", mutableListOf("Kind", "Smart"))
    val person2 = person.deepCopy()
    person.component1()
    person2.qualities.add("brave")
    println(person)
    println(person2)
    
    println("\n=== String extension ===")
    println("Adui".length())
    
//    // Using 'by' keyword - getValue is called when reading
//    var box by Box(10)  // Note: must be 'var' to use setValue
//    println("Initial value: $box")  // Calls getValue() -> prints: 10
//
//    // setValue is called when assigning
//    box = 20  // Calls setValue() -> updates internal value
//    println("After assignment: $box")  // Calls getValue() -> prints: 20
//
//    box = 30
//    println("After another assignment: $box")  // Prints: 30
//
//    println("\n=== Using plus operator ===")
//
//    // Using the + operator - calls plus() function
//    val box1 = Box(5)
//    val box2 = box1 + 10  // Calls box1.plus(10)
//    println("box1.value = ${box1.value}")  // Still 5 (immutable operation)
//    println("box2.value = ${box2.value}")  // 15 (new Box instance)
//
//    val box3 = Box(100) + 50 + 25  // Can chain operations
//    println("box3.value = ${box3.value}")  // 175
//
//    println("\n=== Combining both ===")
//    var mutableBox by Box(1)
//    println("mutableBox = $mutableBox")  // 1
//
//    // You can't directly use + on delegated property, but you can do:
//    val newBox = Box(mutableBox) + 5
//    println("newBox.value = ${newBox.value}")  // 6
//
//    // Or update the delegated property
//    mutableBox = mutableBox + 5  // Reads (getValue), adds, then writes (setValue)
//    println("mutableBox after += 5: $mutableBox")  // 6
}

// ============================================================================
// WHY copy() CANNOT BE OVERRIDDEN
// ============================================================================

data class Product(val id: Int, val name: String, val price: Double) {
    // ✅ equals() CAN be overridden (inherited from Any)
    override fun equals(other: Any?): Boolean {
        return id == (other as? Product)?.id
    }
    
    // ✅ hashCode() CAN be overridden (inherited from Any)
    override fun hashCode(): Int {
        return id.hashCode()
    }
    
    // ❌ copy() CANNOT be overridden - this would cause compilation error!
    /*
    override fun copy(id: Int = this.id, name: String = this.name, price: Double = this.price): Product {
        // This is NOT allowed!
        return Product(id, name, price)
    }
    */
    
    // ✅ But you CAN create a custom copy-like function with a different name
    fun customCopy(id: Int = this.id, name: String = this.name, price: Double = this.price): Product {
        return Product(id, name, price)
    }
    
    // ✅ Or create a deep copy function
    fun deepCopy(): Product {
        return Product(this.id, this.name, this.price)
    }
}

fun demonstrateWhyCopyCannotBeOverridden() {
    println("""
        KEY DIFFERENCE:
        - equals() and hashCode() are methods from Any class → can be overridden
        - copy() is a GENERATED function specific to data classes → cannot be overridden
    """.trimIndent())
    
    println("\n--- Why equals() and hashCode() CAN Be Overridden ---")
    println("""
        equals() and hashCode() are methods inherited from Any (root class):
        
        open class Any {
            open operator fun equals(other: Any?): Boolean
            open fun hashCode(): Int
        }
        
        Since they're 'open', they can be overridden in any class, including data classes.
        This allows you to customize equality logic.
    """.trimIndent())
    
    val product1 = Product(1, "Laptop", 999.99)
    val product2 = Product(1, "Desktop", 799.99)  // Same id, different name/price
    
    println("\n--- Example: Overridden equals() ---")
    println("product1 == product2: ${product1 == product2}")  // true (only compares id)
    println("→ equals() was overridden to compare only id")
    
    println("\n--- Why copy() CANNOT Be Overridden ---")
    println("""
        copy() is NOT inherited from Any. It's a GENERATED function:
        
        1. Generated by compiler based on primary constructor parameters
        2. Has a specific signature: copy(param1: Type1 = this.param1, ...)
        3. Returns the same type as the data class
        4. Cannot be overridden because:
           - It's not a virtual method (not in inheritance hierarchy)
           - It's compiler-generated code
           - Overriding would break type safety and contract
    """.trimIndent())
    
    println("\n--- Example: Using copy() ---")
    val original = Product(1, "Laptop", 999.99)
    val copied = original.copy(name = "Gaming Laptop")  // Uses generated copy()
    println("Original: $original")
    println("Copied: $copied")
    println("→ copy() works with default parameters for all constructor params")
    
    println("\n--- What Would Happen If copy() Could Be Overridden? ---")
    println("""
        Problems that would arise:
        
        1. Type Safety Issues:
           - copy() must return the exact same type
           - Overriding could change return type → breaks polymorphism
        
        2. Signature Confusion:
           - copy() signature is tied to constructor parameters
           - Overriding could change parameters → breaks callers
        
        3. Contract Violation:
           - copy() should create a copy with same type
           - Overriding could return different type → breaks expectations
        
        4. Compiler Complexity:
           - copy() is generated at compile time
           - Allowing override would require runtime dispatch → performance cost
    """.trimIndent())
    
    println("\n--- Workaround: Custom Copy Functions ---")
    val product3 = Product(2, "Phone", 599.99)
    val customCopied = product3.customCopy(name = "Smartphone", price = 699.99)
    println("Original: $product3")
    println("Custom copied: $customCopied")
    println("→ You can create custom copy-like functions with different names")
    
    println("\n--- Summary ---")
    println("""
        equals() and hashCode():
        - Inherited from Any class (open methods)
        - Can be overridden ✅
        - Allows customization of equality logic
        
        copy():
        - Generated by compiler (not inherited)
        - Cannot be overridden ❌
        - Signature tied to constructor parameters
        - Ensures type safety and predictable behavior
        
        Workaround:
        - Create custom functions like customCopy(), deepCopy(), etc.
        - These can have different signatures and behavior
        - But they won't be called by the standard copy() syntax
    """.trimIndent())
}

// ============================================================================
// equals() AND hashCode() CONTRACT CLARIFICATION
// ============================================================================

fun demonstrateEqualsHashCodeContract() {
    println("""
        CLARIFICATION:
        
        ❌ MISCONCEPTION: equals() and hashCode() should always return the same result
        
        ✅ TRUTH: 
        - equals() returns Boolean (true/false)
        - hashCode() returns Int
        - They return DIFFERENT types, so they can't "return the same result"
        
        THE CONTRACT:
        If a.equals(b) == true, then a.hashCode() == b.hashCode()
        
        This means:
        - If two objects are equal (equals() returns true), their hashCodes MUST be equal
        - But if two objects are NOT equal (equals() returns false), their hashCodes CAN be equal (hash collision)
        - equals() does NOT call hashCode() internally
    """.trimIndent())
    
    println("\n--- Example 1: Correct Implementation ---")
    
    class Person(val id: Int, val name: String) {
        override fun equals(other: Any?): Boolean {
            return id == (other as? Person)?.id  // Returns Boolean
        }
        
        override fun hashCode(): Int {
            return id.hashCode()  // Returns Int
        }
    }
    
    val person1 = Person(1, "Alice")
    val person2 = Person(1, "Bob")  // Same id
    val person3 = Person(2, "Alice")  // Different id
    
    println("person1 == person2: ${person1 == person2}")  // true
    println("person1.hashCode(): ${person1.hashCode()}")
    println("person2.hashCode(): ${person2.hashCode()}")
    println("person1.hashCode() == person2.hashCode(): ${person1.hashCode() == person2.hashCode()}")  // true ✅
    println("→ When equals() returns true, hashCodes are equal ✅")
    
    println("\nperson1 == person3: ${person1 == person3}")  // false
    println("person3.hashCode(): ${person3.hashCode()}")
    println("person1.hashCode() == person3.hashCode(): ${person1.hashCode() == person3.hashCode()}")  // false
    println("→ When equals() returns false, hashCodes can differ ✅")
    
    println("\n--- Example 2: Hash Collision (Different Objects, Same HashCode) ---")
    println("""
        IMPORTANT: Hash collisions are allowed!
        
        If equals() returns false, hashCode() CAN still be equal.
        This is called a "hash collision" and is normal.
    """.trimIndent())
    
    class SimpleHash(val value: Int) {
        override fun equals(other: Any?): Boolean {
            return value == (other as? SimpleHash)?.value
        }
        
        override fun hashCode(): Int {
            // Simple hash: just return the value
            return value % 10  // Only uses last digit
        }
    }
    
    val obj1 = SimpleHash(1)
    val obj2 = SimpleHash(11)  // Different value, but same hashCode (both % 10 = 1)
    
    println("obj1 == obj2: ${obj1 == obj2}")  // false (different values)
    println("obj1.hashCode(): ${obj1.hashCode()}")
    println("obj2.hashCode(): ${obj2.hashCode()}")
    println("obj1.hashCode() == obj2.hashCode(): ${obj1.hashCode() == obj2.hashCode()}")  // true!
    println("→ Hash collision: Different objects can have same hashCode ✅")
    println("→ This is ALLOWED by the contract!")
    
    println("\n--- The Contract Rules ---")
    println("""
        RULE 1: If equals() returns true → hashCode() MUST be equal
        ✅ person1 == person2 (true) → person1.hashCode() == person2.hashCode() (true)
        
        RULE 2: If equals() returns false → hashCode() CAN be equal (hash collision)
        ✅ obj1 == obj2 (false) → obj1.hashCode() == obj2.hashCode() (true) is OK
        
        RULE 3: equals() does NOT call hashCode() internally
        ✅ They are independent methods
        
        RULE 4: If equals() returns true but hashCode() differs → CONTRACT VIOLATION ❌
        ❌ This breaks collections (HashMap, HashSet, etc.)
    """.trimIndent())
    
    println("\n--- Example 3: Contract Violation ---")
    
    class BrokenPerson(val id: Int, val name: String) {
        override fun equals(other: Any?): Boolean {
            return id == (other as? BrokenPerson)?.id  // Only compares id
        }
        
        override fun hashCode(): Int {
            return id.hashCode() * 31 + name.hashCode()  // Uses id + name!
            // ❌ PROBLEM: equals() uses only id, hashCode() uses id + name
        }
    }
    
    val broken1 = BrokenPerson(1, "Alice")
    val broken2 = BrokenPerson(1, "Bob")  // Same id, different name
    
    println("broken1 == broken2: ${broken1 == broken2}")  // true (same id)
    println("broken1.hashCode(): ${broken1.hashCode()}")
    println("broken2.hashCode(): ${broken2.hashCode()}")
    println("broken1.hashCode() == broken2.hashCode(): ${broken1.hashCode() == broken2.hashCode()}")  // false!
    
    println("❌ CONTRACT VIOLATION!")
    println("❌ equals() returns true, but hashCodes differ!")
    println("❌ This breaks the contract: if equals() == true, hashCode() MUST be equal")
    
    println("\n--- Summary ---")
    println("""
        ✅ equals() does NOT internally use hashCode()
        ✅ equals() returns Boolean, hashCode() returns Int (different types!)
        ✅ They are independent methods
        
        THE CONTRACT:
        - If equals() returns true → hashCode() MUST be equal
        - If equals() returns false → hashCode() CAN be equal (hash collision is OK)
        - If equals() returns true but hashCode() differs → CONTRACT VIOLATION ❌
        
        Remember:
        - equals() = "Are these objects equal?" (Boolean)
        - hashCode() = "Which bucket should this go in?" (Int)
        - They work together but are independent!
        - The contract ensures consistency for collections
    """.trimIndent())
}

// ============================================================================
// CONTRACT FAILURE WITH INHERITANCE (Base/Derived)
// ============================================================================

fun demonstrateContractFailureWithInheritance() {
    println("""
        YES! Contract failure CAN happen in regular classes with inheritance too!
        
        The same base/derived problem exists, but:
        - Regular classes: You manually implement equals()/hashCode() → you can fix it
        - Data classes: Auto-generated → compiler can't fix it automatically
    """.trimIndent())
    
    println("\n--- Example: Regular Base/Derived with Contract Violation ---")
    
    // Base class
    open class BaseEmployee(val id: Int) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is BaseEmployee) return false
            return id == other.id  // Only compares id
        }
        
        override fun hashCode(): Int {
            return id.hashCode()  // Uses only id
        }
    }
    
    // Derived class
    class DerivedEmployee(id: Int, val department: String) : BaseEmployee(id) {
        // Problem: Should we override equals()?
        // Option 1: Don't override → uses parent's equals() (only compares id)
        // Option 2: Override → compares id + department
        
        // Let's try Option 1 (don't override equals)
        // This means equals() only compares id, but hashCode()...
        
        override fun hashCode(): Int {
            return id.hashCode() * 31 + department.hashCode()  // Uses id + department!
            // ❌ PROBLEM: equals() uses only id (from parent), hashCode() uses id + department
        }
    }
    
    val base1 = BaseEmployee(1)
    val derived1 = DerivedEmployee(1, "Engineering")
    val derived2 = DerivedEmployee(1, "Marketing")  // Same id, different department
    
    println("base1 == derived1: ${base1 == derived1}")  // true (same id)
    println("derived1 == derived2: ${derived1 == derived2}")  // true (same id)
    
    println("base1.hashCode(): ${base1.hashCode()}")
    println("derived1.hashCode(): ${derived1.hashCode()}")
    println("derived2.hashCode(): ${derived2.hashCode()}")
    
    println("base1.hashCode() == derived1.hashCode(): ${base1.hashCode() == derived1.hashCode()}")  // false!
    println("derived1.hashCode() == derived2.hashCode(): ${derived1.hashCode() == derived2.hashCode()}")  // false!
    
    println("❌ CONTRACT VIOLATION!")
    println("❌ equals() returns true, but hashCodes differ!")
    println("❌ This happens because equals() uses only id, but hashCode() uses id + department")
    
    println("\n--- Consequences: HashMap Breaks ---")
    val empMap = mutableMapOf<BaseEmployee, String>()
    empMap[base1] = "Base employee"
    println("Added: BaseEmployee(1)")
    
    val retrieved1 = empMap[derived1]
    val retrieved2 = empMap[derived2]
    println("Getting DerivedEmployee(1, 'Engineering'): $retrieved1")
    println("Getting DerivedEmployee(1, 'Marketing'): $retrieved2")
    println("→ HashMap might not find them even though equals() says they're equal!")
    
    println("\n--- Example: Trying to Fix It (Still Problematic) ---")
    
    // Try to fix by overriding equals() in Derived
    class FixedDerivedEmployee(id: Int, val department: String) : BaseEmployee(id) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is FixedDerivedEmployee) return false
            return id == other.id && department == other.department  // Compares both
        }
        
        override fun hashCode(): Int {
            return id.hashCode() * 31 + department.hashCode()  // Uses both
        }
    }
    
    val fixed1 = FixedDerivedEmployee(1, "Engineering")
    val fixed2 = FixedDerivedEmployee(1, "Marketing")
    
    println("fixed1 == fixed2: ${fixed1 == fixed2}")  // false (different departments)
    println("fixed1.hashCode() == fixed2.hashCode(): ${fixed1.hashCode() == fixed2.hashCode()}")  // false
    
    // But what about comparing BaseEmployee with FixedDerivedEmployee?
    val base2 = BaseEmployee(1)
    println("base2 == fixed1: ${base2 == fixed1}")  // false (different types)
    println("→ Now equals() is consistent, but inheritance still causes confusion!")
    
    println("\n--- The Real Problem with Inheritance ---")
    println("""
        When you have Base and Derived classes:
        
        Problem 1: Should Base(1) == Derived(1, "extra")?
        - Same id → maybe true?
        - But Derived has extra property → maybe false?
        
        Problem 2: If equals() returns true, hashCode() MUST be equal
        - Base(1).hashCode() = hash(id=1)
        - Derived(1, "extra").hashCode() = hash(id=1, extra="extra")
        - These are DIFFERENT! → Contract violation!
        
        Problem 3: Even if you fix it manually:
        - You have to decide: compare all properties or just some?
        - Different derived classes might need different logic
        - It becomes complex and error-prone
        
        Regular Classes:
        - You CAN manually fix it (but it's complex)
        - You have full control
        - But it's easy to make mistakes
        
        Data Classes:
        - Auto-generate equals()/hashCode() based on ALL properties
        - Can't know how to handle inheritance automatically
        - Would always generate inconsistent code
        - So Kotlin prevents inheritance entirely
    """.trimIndent())
    
    println("\n--- Why Data Classes Can't Be Inherited (Summary) ---")
    println("""
        The contract violation problem EXISTS in regular classes too!
        
        But the difference is:
        
        Regular Classes:
        ✅ Can be inherited
        ✅ You manually implement equals()/hashCode()
        ✅ You can (try to) fix contract violations manually
        ⚠️ But it's complex and error-prone
        
        Data Classes:
        ❌ Cannot be inherited
        ❌ Auto-generate equals()/hashCode()
        ❌ Compiler can't know how to handle inheritance
        ✅ Prevents the problem entirely by making them final
        
        The Real Reason:
        - Not that contract violation is unique to data classes
        - But that data classes auto-generate code
        - Auto-generated code can't handle inheritance correctly
        - So Kotlin prevents inheritance to avoid the problem
    """.trimIndent())
}

// ============================================================================
// CONTRACT FAILURE IN REGULAR CLASSES
// ============================================================================

fun demonstrateContractFailureInRegularClasses() {
    println("""
        IMPORTANT POINT:
        Contract failure (equals() and hashCode() inconsistency) can happen in 
        ANY class that overrides equals() and hashCode() incorrectly - not just data classes!
        
        The problem is NOT specific to data classes.
        It's a general problem when equals() and hashCode() are inconsistent.
    """.trimIndent())
    
    println("\n--- Example 1: Regular Class with Contract Violation ---")
    
    // Regular class (NOT a data class) with broken contract
    class RegularEmployee(val id: Int, val name: String, val department: String) {
        // equals() only compares id
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is RegularEmployee) return false
            return id == other.id  // Only compares id
        }
        
        // hashCode() uses id + name + department
        override fun hashCode(): Int {
            return id.hashCode() * 31 + name.hashCode() * 31 + department.hashCode()
            // ❌ PROBLEM: equals() uses only id, but hashCode() uses all properties!
        }
    }
    
    val emp1 = RegularEmployee(1, "Alice", "Engineering")
    val emp2 = RegularEmployee(1, "Bob", "Marketing")  // Same id, different name/dept
    
    println("emp1 == emp2: ${emp1 == emp2}")  // true (same id)
    println("emp1.hashCode(): ${emp1.hashCode()}")
    println("emp2.hashCode(): ${emp2.hashCode()}")
    println("hashCodes equal: ${emp1.hashCode() == emp2.hashCode()}")  // false!
    
    println("❌ CONTRACT VIOLATION in regular class!")
    println("❌ equals() returns true, but hashCodes differ!")
    
    println("\n--- Consequences: HashMap Breaks ---")
    val empMap = mutableMapOf<RegularEmployee, String>()
    empMap[emp1] = "Alice's data"
    println("Added: RegularEmployee(1, 'Alice', 'Engineering')")
    
    val retrieved = empMap[emp2]
    println("Getting RegularEmployee(1, 'Bob', 'Marketing'): $retrieved")
    println("→ HashMap might return null even though equals() says they're equal!")
    println("→ This happens because hashCode() differs, so it looks in wrong bucket!")
    
    println("\n--- Example 2: Data Class with Contract Violation ---")
    
    // Data class with broken contract (overriding incorrectly)
    data class DataEmployee(val id: Int, val name: String, val department: String) {
        // Override equals() to only compare id
        override fun equals(other: Any?): Boolean {
            return id == (other as? DataEmployee)?.id  // Only compares id
        }
        
        // But hashCode() uses all properties (default data class behavior)
        // Actually, if we override equals(), we should also override hashCode()
        // But let's show what happens if we don't:
    }
    
    // Actually, data classes auto-generate hashCode() based on ALL properties
    // So if we override equals() to only compare id, we MUST also override hashCode()
    // Let me show the correct way and the broken way:
    
    println("\n--- Correct Implementation (Both Regular and Data Classes) ---")
    
    class CorrectRegularEmployee(val id: Int, val name: String) {
        override fun equals(other: Any?): Boolean {
            return id == (other as? CorrectRegularEmployee)?.id  // Only compares id
        }
        
        override fun hashCode(): Int {
            return id.hashCode()  // Also uses only id ✅
        }
    }
    
    data class CorrectDataEmployee(val id: Int, val name: String) {
        override fun equals(other: Any?): Boolean {
            return id == (other as? CorrectDataEmployee)?.id  // Only compares id
        }
        
        override fun hashCode(): Int {
            return id.hashCode()  // Also uses only id ✅
        }
    }
    
    val correctRegular1 = CorrectRegularEmployee(1, "Alice")
    val correctRegular2 = CorrectRegularEmployee(1, "Bob")
    println("correctRegular1 == correctRegular2: ${correctRegular1 == correctRegular2}")  // true
    println("hashCodes equal: ${correctRegular1.hashCode() == correctRegular2.hashCode()}")  // true ✅
    
    val correctData1 = CorrectDataEmployee(1, "Alice")
    val correctData2 = CorrectDataEmployee(1, "Bob")
    println("correctData1 == correctData2: ${correctData1 == correctData2}")  // true
    println("hashCodes equal: ${correctData1.hashCode() == correctData2.hashCode()}")  // true ✅
    
    println("\n--- Key Difference: Data Classes vs Regular Classes ---")
    println("""
        Data Classes:
        - Auto-generate equals() and hashCode() based on ALL properties
        - If you override equals(), you MUST also override hashCode() to match
        - Otherwise, auto-generated hashCode() uses all properties → contract violation!
        
        Regular Classes:
        - Do NOT auto-generate equals() or hashCode()
        - You must manually implement both
        - If you implement them inconsistently → contract violation!
        
        The Problem:
        - Contract violation can happen in BOTH data classes AND regular classes
        - It's a general problem when equals() and hashCode() are inconsistent
        - The difference: data classes auto-generate, so you must be careful when overriding
        
        Why Data Classes Can't Be Inherited:
        - NOT because of contract violation (that can happen in any class)
        - But because auto-generated methods would be inconsistent between parent/child
        - The compiler can't know how to handle inheritance automatically
    """.trimIndent())
    
    println("\n--- Summary ---")
    println("""
        ✅ Contract failure CAN happen in regular classes
        ✅ Contract failure CAN happen in data classes
        ✅ It's a general problem when equals() and hashCode() are inconsistent
        
        Rule:
        - If equals() uses property X, hashCode() MUST also use property X
        - If equals() ignores property Y, hashCode() MUST also ignore property Y
        - This applies to ALL classes (regular, data, abstract, etc.)
        
        Data Classes:
        - Auto-generate equals() and hashCode() based on ALL properties
        - If you override equals(), you MUST override hashCode() to match
        - Otherwise, auto-generated hashCode() will use all properties → violation!
        
        Regular Classes:
        - You manually implement equals() and hashCode()
        - You must ensure they're consistent
        - No auto-generation, so you have full control (and full responsibility!)
    """.trimIndent())
}

// ============================================================================
// DOES equals() USE hashCode() INTERNALLY?
// ============================================================================

class TestEquals(val id: Int, val name: String) {
    var hashCodeCallCount = 0
    var equalsCallCount = 0
    
    override fun equals(other: Any?): Boolean {
        equalsCallCount++
        println("  → equals() called (call #$equalsCallCount)")
        println("  → equals() does NOT call hashCode() - they're independent!")
        
        if (this === other) return true
        if (other !is TestEquals) return false
        
        // equals() compares properties directly - NO hashCode() call!
        return id == other.id && name == other.name
    }
    
    override fun hashCode(): Int {
        hashCodeCallCount++
        println("  → hashCode() called (call #$hashCodeCallCount)")
        return id.hashCode() * 31 + name.hashCode()
    }
}

fun demonstrateEqualsAndHashCodeIndependence() {
    println("""
        COMMON MISCONCEPTION:
        Many people think equals() internally uses hashCode() to determine equality.
        
        TRUTH:
        equals() and hashCode() are COMPLETELY INDEPENDENT methods!
        equals() does NOT call hashCode() internally.
    """.trimIndent())
    
    println("\n--- Proof: equals() Works Without hashCode() ---")
    val obj1 = TestEquals(1, "Alice")
    val obj2 = TestEquals(1, "Alice")
    
    println("Comparing obj1 == obj2:")
    val result = obj1 == obj2
    println("Result: $result")
    println("equals() was called ${obj1.equalsCallCount} time(s)")
    println("hashCode() was called ${obj1.hashCodeCallCount} time(s)")
    println("→ equals() did NOT call hashCode()!")
    
    println("\n--- When Does hashCode() Get Called? ---")
    println("""
        hashCode() is called by COLLECTIONS (HashMap, HashSet, etc.), NOT by equals():
        
        1. HashMap.put(key, value):
           - Calls key.hashCode() → finds bucket
           - Stores in that bucket
           
        2. HashMap.get(key):
           - Calls key.hashCode() → finds bucket (FAST lookup)
           - Then calls equals() on objects in that bucket (to verify exact match)
           
        3. HashSet.contains(element):
           - Calls element.hashCode() → finds bucket
           - Then calls equals() to verify
           
        Process:
        hashCode() → Find bucket (FAST, O(1))
        equals() → Verify exact match (slower, but accurate)
    """.trimIndent())
    
    println("\n--- Demonstration: HashMap Usage ---")
    val map = mutableMapOf<TestEquals, String>()
    val key1 = TestEquals(1, "Alice")
    val key2 = TestEquals(1, "Alice")  // Same id and name
    
    println("\n1. Adding key1 to map:")
    map[key1] = "Value 1"
    println("   hashCode() called: ${key1.hashCodeCallCount} time(s)")
    println("   equals() called: ${key1.equalsCallCount} time(s)")
    
    println("\n2. Getting value with key2:")
    val value = map[key2]
    println("   Result: $value")
    println("   hashCode() called: ${key2.hashCodeCallCount} time(s)")
    println("   equals() called: ${key2.equalsCallCount} time(s)")
    println("   → HashMap calls hashCode() FIRST, then equals() to verify!")
    
    println("\n--- The Contract (Not Implementation) ---")
    println("""
        The relationship between equals() and hashCode() is a CONTRACT, not implementation:
        
        CONTRACT:
        If a.equals(b) == true, then a.hashCode() == b.hashCode()
        
        This means:
        - equals() does NOT call hashCode() internally
        - They are independent methods
        - But they MUST be consistent (follow the contract)
        - Collections use hashCode() for performance, equals() for accuracy
        
        Why the contract exists:
        - Collections use hashCode() to find the right "bucket" quickly
        - Then use equals() to find the exact match in that bucket
        - If contract is broken, collections malfunction!
    """.trimIndent())
    
    println("\n--- Example: What Happens When Contract is Broken ---")
    class BrokenContract(val id: Int, val name: String) {
        override fun equals(other: Any?): Boolean {
            return id == (other as? BrokenContract)?.id  // Only compares id
        }
        
        override fun hashCode(): Int {
            return id.hashCode() * 31 + name.hashCode()  // Uses id + name!
            // ❌ PROBLEM: equals() uses only id, hashCode() uses id + name
        }
    }
    
    val broken1 = BrokenContract(1, "Alice")
    val broken2 = BrokenContract(1, "Bob")  // Same id, different name
    
    println("broken1 == broken2: ${broken1 == broken2}")  // true (same id)
    println("broken1.hashCode(): ${broken1.hashCode()}")
    println("broken2.hashCode(): ${broken2.hashCode()}")
    println("hashCodes equal: ${broken1.hashCode() == broken2.hashCode()}")  // false!
    
    val brokenMap = mutableMapOf<BrokenContract, String>()
    brokenMap[broken1] = "Found"
    println("\nMap contains broken1: ${brokenMap.containsKey(broken1)}")
    println("Map contains broken2: ${brokenMap.containsKey(broken2)}")  // Might be false!
    println("→ Even though equals() says they're equal, HashMap might not find it!")
    println("→ This is because hashCode() differs, so it looks in wrong bucket!")
    
    println("\n--- Summary ---")
    println("""
        ✅ equals() does NOT use hashCode() internally
        ✅ They are completely independent methods
        ✅ equals() compares properties directly
        ✅ hashCode() is used by collections for performance (bucket lookup)
        ✅ Collections call hashCode() FIRST, then equals() to verify
        
        The Contract:
        - If equals() returns true, hashCode() MUST be equal
        - This is a requirement, not an implementation detail
        - Breaking the contract causes collections to malfunction
        
        Remember:
        - equals() = "Are these objects equal?" (compares properties)
        - hashCode() = "Which bucket should this go in?" (used by collections)
        - They work together but are independent!
    """.trimIndent())
}

// ============================================================================
// equals() AND hashCode() RELATIONSHIP
// ============================================================================

data class User(val id: Int, val name: String) {
    override fun equals(other: Any?): Boolean {
        return id == (other as? User)?.id
    }
    
    override fun hashCode(): Int {
        return id.hashCode()
    }
}

// Example showing what happens when equals() and hashCode() are INCONSISTENT
class BadUser(val id: Int, val name: String) {
    override fun equals(other: Any?): Boolean {
        return id == (other as? BadUser)?.id  // Only compares id
    }
    
    override fun hashCode(): Int {
        return id.hashCode() * 31 + name.hashCode()  // Uses BOTH id AND name!
        // ❌ PROBLEM: equals() uses only id, but hashCode() uses id + name
        // This violates the contract!
    }
}

fun demonstrateEqualsAndHashCode() {
    println("""
        THE CONTRACT:
        If a.equals(b) == true, then a.hashCode() MUST equal b.hashCode()
        
        This is CRITICAL for collections like HashMap, HashSet, etc.
    """.trimIndent())
    
    println("\n--- Your User Example (CORRECT) ---")
    val user1 = User(1, "Alice")
    val user2 = User(1, "Bob")  // Same id, different name
    
    println("user1 == user2: ${user1 == user2}")  // true (same id)
    println("user1.hashCode(): ${user1.hashCode()}")
    println("user2.hashCode(): ${user2.hashCode()}")
    println("hashCodes equal: ${user1.hashCode() == user2.hashCode()}")  // true
    
    println("✅ CORRECT: equals() compares id, hashCode() uses id")
    println("✅ Contract satisfied: equal objects have same hashCode")
    
    println("\n--- What hashCode() Does ---")
    println("""
        hashCode() is used by collections for FAST lookup:
        
        1. HashMap/HashSet use hashCode() to determine which "bucket" to store objects
        2. When searching, they first check hashCode() (fast)
        3. Then use equals() to verify (slower, but accurate)
        
        Process:
        - put(key, value): Calculate key.hashCode() → find bucket → store
        - get(key): Calculate key.hashCode() → find bucket → use equals() to find exact match
    """.trimIndent())
    
    println("\n--- Example: Using User in HashMap ---")
    val userMap = mutableMapOf<User, String>()
    val u1 = User(1, "Alice")
    val u2 = User(1, "Bob")  // Same id as u1
    
    userMap[u1] = "First user"
    println("Added: User(1, 'Alice') -> 'First user'")
    
    println("Getting User(1, 'Bob'): ${userMap[u2]}")  // Should find it!
    println("→ HashMap uses hashCode() first (finds bucket), then equals() (verifies match)")
    println("→ Since u1.hashCode() == u2.hashCode() and u1 == u2, it finds the value!")
    
    println("\n--- Example: Using User in HashSet ---")
    val userSet = mutableSetOf<User>()
    val us1 = User(1, "Alice")
    val us2 = User(1, "Bob")  // Same id
    
    userSet.add(us1)
    println("Added User(1, 'Alice')")
    println("Set contains User(1, 'Bob'): ${userSet.contains(us2)}")  // true!
    println("Set size: ${userSet.size}")  // 1 (duplicate not added)
    println("→ HashSet uses hashCode() + equals() to check for duplicates")
    
    println("\n--- What Happens When Contract is BROKEN (BadUser) ---")
    val bad1 = BadUser(1, "Alice")
    val bad2 = BadUser(1, "Bob")  // Same id, different name
    
    println("bad1 == bad2: ${bad1 == bad2}")  // true (same id)
    println("bad1.hashCode(): ${bad1.hashCode()}")
    println("bad2.hashCode(): ${bad2.hashCode()}")
    println("hashCodes equal: ${bad1.hashCode() == bad2.hashCode()}")  // false!
    
    println("❌ PROBLEM: equals() returns true, but hashCodes are different!")
    println("❌ This VIOLATES the contract!")
    
    println("\n--- Consequences: HashMap Breaks ---")
    val badMap = mutableMapOf<BadUser, String>()
    badMap[bad1] = "First user"
    println("Added: BadUser(1, 'Alice') -> 'First user'")
    
    val retrieved = badMap[bad2]  // Might return null!
    println("Getting BadUser(1, 'Bob'): $retrieved")
    println("→ HashMap might not find it because hashCodes differ!")
    println("→ Even though equals() says they're equal!")
    println("→ This causes BUGS in collections!")
    
    println("\n--- Summary ---")
    println("""
        Your User implementation is CORRECT:
        - equals() compares only id
        - hashCode() uses only id
        - Contract is satisfied ✅
        
        hashCode() purpose:
        - Used by HashMap, HashSet, etc. for fast bucket lookup
        - Must be consistent with equals()
        - If two objects are equal (equals() == true), they MUST have same hashCode()
        - If two objects have same hashCode(), they might NOT be equal (hash collision)
        
        Rule of thumb:
        - If equals() uses property X, hashCode() should also use property X
        - If equals() ignores property Y, hashCode() should also ignore property Y
    """.trimIndent())
}

// ============================================================================
// WHY DATA CLASSES CANNOT BE INHERITED FROM
// ============================================================================

/*
 * PROBLEM 1: equals() and hashCode() Contract Violation
 * 
 * Data classes automatically generate equals() and hashCode() based on ALL properties.
 * If inheritance were allowed, we'd have this problem:
 */

// This is what WOULD happen if data classes could be inherited (but it's NOT allowed):
/*
data class Base(val id: Int)
class Derived(val id: Int, val extra: String) : Base(id)

// Problem: Should Base(1) equal Derived(1, "extra")?
// - They have the same 'id'
// - But Derived has additional 'extra' property
// - equals() contract: if a == b, then a.hashCode() == b.hashCode()
// - But Base(1).hashCode() != Derived(1, "extra").hashCode()
// - This BREAKS the contract!
*/

fun demonstrateWhyDataClassesCannotBeInherited() {
    println("""
        Data classes automatically generate:
        1. equals() - compares ALL properties structurally
        2. hashCode() - based on ALL properties  
        3. toString() - includes ALL properties
        4. copy() - copies ALL properties
        5. componentN() - destructuring for ALL properties
        
        If inheritance were allowed, these would break. Let's see why:
    """.trimIndent())
    
    // Show what happens with regular classes that CAN be inherited
    println("\n--- Example 1: Regular Classes CAN Be Inherited ---")
    open class RegularBase(val id: Int)
    class RegularDerived(id: Int, val extra: String) : RegularBase(id)
    
    val base = RegularBase(1)
    val derived = RegularDerived(1, "extra")
    
    println("base == derived: ${base == derived}")  // false (uses default equals = referential)
    println("base === derived: ${base === derived}")  // false
    println("→ Regular classes can be inherited, but equals() is NOT auto-generated")
    println("→ You must manually implement equals()/hashCode() if needed")
    
    // Now show what WOULD break if data classes could be inherited
    println("\n--- Problem 1: equals() and hashCode() Contract Violation ---")
    println("""
        If this were allowed (but it's NOT):
        
        data class Base(val id: Int)
        class Derived(val id: Int, val extra: String) : Base(id)
        
        Question: Should Base(1) == Derived(1, "extra")?
        
        Data class equals() compares ALL properties:
        - Base(1) has: id=1
        - Derived(1, "extra") has: id=1, extra="extra"
        - Are they equal? Same id, but different properties!
        
        hashCode() problem:
        - Base(1).hashCode() = hash(id=1)
        - Derived(1, "extra").hashCode() = hash(id=1, extra="extra")
        - These are DIFFERENT!
        
        CONTRACT VIOLATION:
        If equals() returns true, hashCode() MUST be equal!
        But Base(1).hashCode() != Derived(1, "extra").hashCode()
        → This BREAKS the contract!
        → Collections (HashMap, HashSet) would malfunction!
    """.trimIndent())
    
    // Demonstrate the contract violation with a practical example
    println("\n--- Practical Example: What Would Break ---")
    
    // Simulate what would happen (using regular classes to show the concept)
    class SimulatedBase(val id: Int) {
        // Simulate data class equals() - compares all properties
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is SimulatedBase) return false
            return id == other.id  // Only compares id (Base only has id)
        }
        
        override fun hashCode(): Int = id.hashCode()
    }
    
    class SimulatedDerived(id: Int, val extra: String) : SimulatedBase(id) {
        // If this were a data class, equals() would compare id + extra
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is SimulatedDerived) return false
            return id == other.id && extra == other.extra  // Compares BOTH
        }
        
        override fun hashCode(): Int = id.hashCode() * 31 + extra.hashCode()
    }
    
    val simBase = SimulatedBase(1)
    val simDerived = SimulatedDerived(1, "extra")
    
    println("simBase == simDerived: ${simBase == simDerived}")  // false (different types)
    println("simBase.hashCode(): ${simBase.hashCode()}")
    println("simDerived.hashCode(): ${simDerived.hashCode()}")
    println("→ Even with manual implementation, inheritance causes confusion")
    
    println("\n--- Problem 2: copy() Ambiguity ---")
    println("""
        If Derived could inherit from data class Base:
        
        val derived = Derived(1, "extra")
        val copied = derived.copy()  // What should this return?
        
        Options:
        1. Base instance? → loses 'extra' property ❌
        2. Derived instance? → but copy() is from Base ❌
        3. Which properties should be copied? ❌
        
        → copy() signature is tied to constructor parameters
        → Inheritance breaks this contract
    """.trimIndent())
    
    println("\n--- Problem 3: componentN() Confusion ---")
    println("""
        Destructuring would be unclear:
        
        val derived = Derived(1, "extra")
        val (id) = derived  // Which component?
        
        Options:
        1. Just 'id'? → ignores 'extra' ❌
        2. Both 'id' and 'extra'? → but Base only has one component ❌
        
        → componentN() functions are generated based on constructor params
        → Inheritance breaks destructuring
    """.trimIndent())
    
    println("\n--- Problem 4: toString() Inconsistency ---")
    println("""
        Data class toString() includes ALL properties.
        
        If Derived inherits from Base:
        - Should toString() include parent properties?
        - Should toString() include child properties?
        - How to format it consistently?
        
        → toString() generation becomes ambiguous
    """.trimIndent())
    
    println("\n--- SOLUTION: Make Data Classes Final ---")
    println("""
        Kotlin prevents these problems by making data classes 'final' (cannot be inherited).
        
        Benefits:
        ✅ equals() and hashCode() are always consistent
        ✅ copy() always works correctly  
        ✅ componentN() is always clear
        ✅ toString() is always predictable
        ✅ No ambiguity or contract violations
        
        Alternatives if you need inheritance:
        1. Regular classes (not data classes) - can be inherited
        2. Interfaces - for common contracts
        3. Sealed classes - for closed hierarchies
        4. Abstract classes - for common behavior
        5. Composition - "has-a" instead of "is-a"
    """.trimIndent())
    
    println("\n--- Real Example: What Works ---")
    // Show that data classes CAN inherit FROM other classes
    open class Animal(val species: String)
    data class Dog(val name: String, species: String) : Animal(species)
    
    val dog1 = Dog("Buddy", "Canine")
    val dog2 = Dog("Buddy", "Canine")
    println("dog1 == dog2: ${dog1 == dog2}")  // true (structural equality)
    println("dog1.copy(name = 'Max'): ${dog1.copy(name = "Max")}")
    println("→ Data classes CAN inherit FROM other classes (if parent is 'open')")
    println("→ But data classes CANNOT BE inherited FROM (they're final)")
}

data class Person(val firstName: String, val lastName: String, val qualities: MutableList<String>) {

    fun deepCopy() : Person {
        val qualities = this.qualities.toMutableList()
        return Person(this.firstName, this.lastName, qualities)
    }

}

class DemoClass {
    val name by SimpleLazy<String> { "Demo" }
}

class Box(var value: Int) {
    operator fun getValue(thisRef: Any?, property: KProperty<*>): Int {
        return value
    }

    operator fun setValue(thisRef: Any?, property: KProperty<*>, newValue: Int) {
        value = newValue
    }

    operator fun plus(other: Int): Box {
        return Box(this.value + other)
    }
}


fun String.length(): Int {
    return this.length
}

class SimpleLazy<T>(val initializer: () -> T) {
    @Volatile
    private var value: T? = null

    operator fun getValue(thisRef: Any?, property: KProperty<*>): T {
        // thisRef: The object instance where the property is accessed
        //          - null if accessed from top-level (like in main())
        //          - The object instance if accessed from a class (like DemoClass)
        // property: Contains metadata about the property
        //           - property.name: "x", "name", etc.
        //           - property.returnType: The type of the property
        
        // For lazy initialization, we don't actually need these parameters
        // but they're required by Kotlin's delegation protocol
        
        if (value == null) {
            synchronized(this) {
                if (value == null) {
                    value = initializer.invoke()
                }
            }
        }
        return value!!
    }
}




